VERILOG_SOURCES += ../../common/timescale.v ../../../../../../simWorkspace/UdpApp/rtl/UdpApp.v
TOPLEVEL=UdpApp
MODULE=UdpAppOnNetwork

# Python path to cocotblib
export PYTHONPATH:=../..
include $(shell cocotb-config --makefiles)/Makefile.sim
