VERILOG_SOURCES += ../../common/timescale.v ../../../../../../simWorkspace/UdpCtrl/rtl/UdpCtrl.v
TOPLEVEL=UdpCtrl
MODULE=UdpCtrlTest

# Python path to cocotblib
export PYTHONPATH:=../..
include $(shell cocotb-config --makefiles)/Makefile.sim
